"""
gen_vlw.py  –  Generate TFT_eSPI VLW smooth-font C headers from Windows TTF fonts.

Usage:
    python tools/gen_vlw.py
"""
import struct, os
import freetype

CHARS = ''.join(chr(c) for c in range(32, 127))   # printable ASCII 0x20..0x7E


def read_bitmap(bm):
    """Return a bytes object of 8-bit alpha values from a FreeType bitmap."""
    if bm.pixel_mode == freetype.FT_PIXEL_MODE_GRAY:
        return bytes(bm.buffer[: bm.rows * bm.width])
    if bm.pixel_mode == freetype.FT_PIXEL_MODE_MONO:
        out = bytearray()
        for row in range(bm.rows):
            for col in range(bm.width):
                byte  = bm.buffer[row * bm.pitch + col // 8]
                bit   = (byte >> (7 - col % 8)) & 1
                out.append(255 if bit else 0)
        return bytes(out)
    return bytes()


def generate_vlw(font_path, pixel_height, output_path, array_name, chars=CHARS):
    """
    Generate a TFT_eSPI VLW font array and write it as a C header file.

    VLW binary layout (all big-endian):
      Header  – 6 x uint32  (24 bytes)
      Metrics – gCount x 7 x int32  (28 bytes each)
      Bitmaps – concatenated alpha bytes
    """
    face = freetype.Face(font_path)
    face.set_pixel_sizes(0, pixel_height)

    metrics  = face.size
    ascent   = int(metrics.ascender  / 64)
    descent  = abs(int(metrics.descender / 64))

    glyphs = []
    for ch in chars:
        code = ord(ch)
        if face.get_char_index(ch) == 0 and ch != ' ':
            continue
        face.load_char(ch, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
        g  = face.glyph
        bm = g.bitmap
        w  = bm.width
        h  = bm.rows
        pixels = read_bitmap(bm) if (w > 0 and h > 0) else bytes()
        glyphs.append({
            'unicode': code,
            'height':  h,
            'width':   w,
            'advance': max(1, int(g.advance.x / 64)),
            'dy':      g.bitmap_top,        # +ve = up from baseline
            'dx':      g.bitmap_left,       # signed; left offset from cursor
            'pixels':  pixels,
        })

    # ---- build binary ----
    data = bytearray()
    # Header
    data += struct.pack('>I', len(glyphs))
    data += struct.pack('>I', 11)             # vlw version
    data += struct.pack('>I', pixel_height)   # yAdvance hint
    data += struct.pack('>I', 0)              # deprecated mboxY
    data += struct.pack('>I', ascent)
    data += struct.pack('>I', descent)
    # Per-glyph metrics
    for g in glyphs:
        data += struct.pack('>i', g['unicode'])
        data += struct.pack('>i', g['height'])
        data += struct.pack('>i', g['width'])
        data += struct.pack('>i', g['advance'])
        data += struct.pack('>i', g['dy'])
        data += struct.pack('>i', g['dx'])
        data += struct.pack('>i', 0)          # padding
    # Bitmaps
    for g in glyphs:
        data += g['pixels']
    # Trailing font name + anti-alias marker
    name_b = array_name.encode('ascii')
    data += bytes([len(name_b)])
    data += name_b
    data += bytes([0, 1])

    # ---- write C header ----
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w', newline='\n') as f:
        f.write(f"// TFT_eSPI smooth (VLW) font – {array_name}\n")
        f.write(f"// Source : {os.path.basename(font_path)}, "
                f"pixel_height={pixel_height}, "
                f"ascent={ascent}, descent={descent}, "
                f"glyphs={len(glyphs)}\n")
        f.write(f"// Auto-generated by tools/gen_vlw.py – do not edit.\n")
        f.write(f"#pragma once\n\n")
        f.write(f"const uint8_t {array_name}[] = {{\n")
        cols = 16
        for i in range(0, len(data), cols):
            chunk = data[i : i + cols]
            f.write('  ' + ', '.join(f'0x{b:02X}' for b in chunk) + ',\n')
        f.write('};\n')

    print(f"  {output_path}  ({len(glyphs)} glyphs, {len(data):,} bytes)")


if __name__ == '__main__':
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    fonts_dir = os.path.join(root, 'main', 'fonts')

    print("Generating VLW font headers …")

    # Large bold numbers – panel sensor values
    generate_vlw(
        'C:/Windows/Fonts/arialbd.ttf',
        pixel_height=36,
        output_path=os.path.join(fonts_dir, 'Arial_Bold_36.h'),
        array_name='Arial_Bold_36',
    )

    # Smaller regular – panel titles, units, category labels, header text
    generate_vlw(
        'C:/Windows/Fonts/arial.ttf',
        pixel_height=16,
        output_path=os.path.join(fonts_dir, 'Arial_Regular_16.h'),
        array_name='Arial_Regular_16',
    )

    print("Done.")
